version: '3'

services:
  rqd:
    image: ${REGISTRY_SERVER}/demo_rqd:latest
    build:
      context: ./
      dockerfile: ./rqd.dockerfile
      args:
        OPENCUE_MAJOR : 0
        OPENCUE_MINOR : 21
        OPENCUE_PATCH : 13