apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    descriptor: cuebot
  name: cuebot
spec:
  ports:
  - name: "8443"
    port: 8443
    targetPort: 8443
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    descriptor: cuebot
status:
  loadBalancer: {}
