apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    descriptor: db
  name: db
spec:
  ports:
  - name: "5432"
    port: 5432
    targetPort: 5432
  selector:
    descriptor: db
status:
  loadBalancer: {}
