apiVersion: v1
kind: Service
metadata:
  annotations:
  creationTimestamp: null
  labels:
    descriptor: rqd
  name: rqd
spec:
  ports:
  - name: "8444"
    port: 8444
    targetPort: 8444
  selector:
    descriptor: rqd
status:
  loadBalancer: {}
