version: '3'

services:
  blender_rqd:
    image: ${REGISTRY_SERVER}/demo_blender:latest
    build:
      context: ./rendernode/blender
      dockerfile: ./blender.dockerfile
      args:
        BLENDER_MAJOR : 3
        BLENDER_MINOR : 6
        BLENDER_PATCH : 1
        REGISTRY_SERVER : ${REGISTRY_SERVER}
  ffmpeg_rqd:
    image: ${REGISTRY_SERVER}/demo_ffmpeg:latest
    build:
      context: ./rendernode/ffmpeg
      dockerfile: ./ffmpeg.dockerfile
      args:
        REGISTRY_SERVER : ${REGISTRY_SERVER}
  nuke_rqd:
    image: ${REGISTRY_SERVER}/demo_nuke:latest
    build:
      context: ./rendernode/nuke
      dockerfile: ./nuke.dockerfile
      args:
        REGISTRY_SERVER : ${REGISTRY_SERVER}
        foundry_LICENSE : ${FOUNDRY_NUKE_LIC_HOST}