services:
  blender_rqd:
    image: ${REGISTRY_SERVER}/demo_blender:latest
    build:
      context: ./rendernode/blender
      dockerfile: ./blender.dockerfile
      args:
        BLENDER_MAJOR : 4
        BLENDER_MINOR : 2
        BLENDER_PATCH : 3
        REGISTRY_SERVER : ${REGISTRY_SERVER}
  ffmpeg_rqd:
    image: ${REGISTRY_SERVER}/demo_ffmpeg:latest
    build:
      context: ./rendernode/ffmpeg
      dockerfile: ./ffmpeg.dockerfile
      args:
        REGISTRY_SERVER : ${REGISTRY_SERVER}